### ISSUE TITLE
How to serve static files?

### ISSUE THREAD

**Issue by vasily-kirichenko** [SuaveIO/Suave.IIS#10]
I'm having problems trying to serve Fable generated files. 

I put all output of `dotnet publish` into the root folder and `index.html`, `bundle.js` and `bundle.js.map` to `public` subfolder. 

Suave config

```fsharp
let webpart =
        choose [
            GET >=> Files.browseHome
            GET >=> path "/" >=> Files.file "index.html"
            GET >=> choose [ ... ]
            NOT_FOUND "Page not found."
        ] >=> logWithLevelStructured Logging.Info logger logFormatStructured

    let logger = Logging.Targets.create Logging.Info [| "Suave" |]

    let config = { defaultConfig with bindings = [ HttpBinding.create HTTP IPAddress.Any 8085us ]
                                      homeFolder = Some (Path.GetFullPath "./public")
                                      logger = Logging.Targets.create Logging.LogLevel.Info [|"ServerCode"; "Server" |] }
                 |> IIS.Configuration.withPort argv
    startWebServer config webpart
```
and when I go to `/`, I get "page not found".

Any ideas how to fix this?

**Comment by Dzoukr** [comment]
Hi @vasily-kirichenko I can remember I had some issue like this - https://github.com/SuaveIO/suave/issues/562#issuecomment-287022956

I had to create custom function.

**Comment by vasily-kirichenko** [comment]
I've moved to Giraffe. Thanks anyway :)

**Comment by Dzoukr** [comment]
It looks like all community goes this way :) Sorry I didn't help.
