### ISSUE TITLE
Not compatible with Suave 2

### ISSUE THREAD

**Issue by rojepp** [SuaveIO/Suave.IIS#2]
> System.MissingMethodException: Method not found: 'Void Suave.SuaveConfig..ctor(Microsoft.FSharp.Collections.FSharpList`1<HttpBinding>, Byte[], Microsoft.FSharp.Core.FSharpFunc`2<System.Exception,Microsoft.FSharp.Core.FSharpFunc`2<System.String,Microsoft.FSharp.Core.FSharpFunc`2<HttpContext,Microsoft.FSharp.Control.FSharpAsync`1<Microsoft.FSharp.Core.FSharpOption`1<HttpContext>>>>>, System.TimeSpan, System.Threading.CancellationToken, Int32, Int32, Microsoft.FSharp.Core.FSharpFunc`2<System.String,Microsoft.FSharp.Core.FSharpOption`1<MimeType>>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Suave.Logging.Logger, Suave.TcpServerFactory, Suave.CookieSerialiser, TlsProvider, Boolean)'.

**Comment by Dzoukr** [comment]
Hi @rojepp, thanks a lot for notifying. New version is now public and ready for Suave v2.0.

**Comment by rojepp** [comment]
Ha, got this notification just as I was about to open a PR for it 😄 
https://github.com/rojepp/Suave.IIS/tree/Suave_2

Great work, thanks, I'll give it a spin

**Comment by Dzoukr** [comment]
Thanks! If anything goes wrong, please, let me know. 👍
