### ISSUE TITLE
Move to SuaveIO org?

### ISSUE THREAD

**Issue by haf** [SuaveIO/Suave.IIS#3]
Hi Roman Provazník,

What would you say about moving this to SuaveIO as a subrepo? You'll get access to this repo to continue maintaining it, of course.

/cc @ademar

Cheers,
Henrik

**Comment by Dzoukr** [comment]
Hi Henrik,

as a big fan of your work, it would be honor for me!

What needs to be done from my side?

Cheers,
Roman

**Comment by haf** [comment]
You need to initiate the transfer to the SuaveIO organisation. Let's wait for @ademar to weigh in before we do it, though.

**Comment by Dzoukr** [comment]
Ok, just let me know. 👍

**Comment by ademar** [comment]
Sure I think it would be great;  you would become a member of the SuaveIO organization :)

**Comment by Dzoukr** [comment]
Done! :) Maybe we should now change Nuget template?
