### ISSUE TITLE
Get authenticated windows user name

### ISSUE THREAD

**Issue by vasily-kirichenko** [SuaveIO/Suave.IIS#9]
@Dzoukr Do you know if it's possible to get authenticated with windows auth user name in a Suave handler? Maybe it's in a header or somewhere else?

**Comment by Dzoukr** [comment]
Hi @vasily-kirichenko, it is definitely possible. You need to:

- set windows auth only on IIS (disable others, especially anonymous)
- set `forwardWindowsAuthToken="true"` in web.config (see one in this repo)
- use this code :)

```fsharp
let private getIdentityForIISToken header = 
    match Int32.TryParse(header, System.Globalization.NumberStyles.HexNumber, System.Globalization.CultureInfo.InvariantCulture) with
    | (true, value) -> 
        let handle = new IntPtr(value)
        new WindowsIdentity(handle) |> Some
    | (false, _) -> None
```

where `header` is string parsed from `ctx.request.headers` as
- `ms-aspnetcore-winauthtoken` for aspNetCore handler
- `x-iis-windowsauthtoken` for httpplatformhandler

Hope it helps (if so, please close the issue ;))

Cheers.

**Comment by Dzoukr** [comment]
And you need to open `System.Security.Principal` - should be enough.

**Comment by vasily-kirichenko** [comment]
@Dzoukr I works like a charm, thank you a lot! :)
